using Backtrace.Unity.Common;
using Backtrace.Unity.Types;
using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

namespace Backtrace.Unity.Model.Database
{
    /// <summary>
    /// Backtrace Database attachment manager. Manage built-in BacktraceDatabase attachments
    /// </summary>
    internal class BacktraceDatabaseAttachmentManager
    {
        internal int ScreenshotMaxHeight { get; set; } = Screen.height;
        internal int ScreenshotQuality { get; set; } = 90;

        private readonly BacktraceDatabaseSettings _settings;
        private float _lastScreenTime;
        private string _lastScreenPath;
        private readonly object _lock = new object();
        public BacktraceDatabaseAttachmentManager(BacktraceDatabaseSettings settings)
        {
            _settings = settings;
        }

        public IEnumerable<string> GetReportAttachments(BacktraceData data)
        {
            var attachmentPrefix = data.UuidString;

            var result = new List<string>();
            AddIfPathIsNotEmpty(result, GetScreenshotPath(attachmentPrefix));
            AddIfPathIsNotEmpty(result, GetUnityPlayerLogFile(data, attachmentPrefix));
            AddIfPathIsNotEmpty(result, GetMinidumpPath(data, attachmentPrefix));
            return result;
        }

        private void AddIfPathIsNotEmpty(List<string> source, string attachmentPath)
        {
            if (!string.IsNullOrEmpty(attachmentPath))
            {
                source.Add(attachmentPath);
            }
        }

        private string GetMinidumpPath(BacktraceData backtraceData, string dataPrefix)
        {
            if (_settings.MinidumpType == MiniDumpType.None)
            {
                return string.Empty;
            }
            //note that every minidump file generated by app ends with .dmp extension
            //its important information if you want to clear minidump file
            string minidumpDestinationPath = Path.Combine(_settings.DatabasePath, string.Format("{0}-dump.dmp", dataPrefix));
            var backtraceReport = backtraceData.Report;
            if (backtraceReport == null)
            {
                return string.Empty;
            }
            MinidumpException minidumpExceptionType = backtraceReport.ExceptionTypeReport
                ? MinidumpException.Present
                : MinidumpException.None;

            bool minidumpSaved = MinidumpHelper.Write(
                filePath: minidumpDestinationPath,
                options: _settings.MinidumpType,
                exceptionType: minidumpExceptionType);

            return minidumpSaved
                ? minidumpDestinationPath
                : string.Empty;
        }

        /// <summary>
        /// Get path to game screenshot when exception occured
        /// </summary>
        /// <returns>Path to game screenshot</returns>
        private string GetScreenshotPath(string dataPrefix)
        {
            if (!_settings.GenerateScreenshotOnException)
            {
                return string.Empty;
            }
            var screenshotPath = Path.Combine(_settings.DatabasePath, string.Format("{0}-screen.jpg", dataPrefix));

            lock (_lock)
            {
                if (BacktraceDatabase.LastFrameTime == _lastScreenTime)
                {
                    if (File.Exists(_lastScreenPath))
                    {
                        File.Copy(_lastScreenPath, screenshotPath);
                        return screenshotPath;
                    }
                    return _lastScreenPath;
                }
                else
                {
                    Texture2D result;
                    if (ScreenshotMaxHeight < Screen.height)
                    {

                        float ratio = Screen.width / Screen.height;
                        int targetHeight = Mathf.Min(Screen.height, ScreenshotMaxHeight);
                        int targetWidth = Mathf.RoundToInt(targetHeight * ratio);

#if UNITY_2019_1_OR_NEWER
                        RenderTexture screenTexture = RenderTexture.GetTemporary(Screen.width, Screen.height);
                        ScreenCapture.CaptureScreenshotIntoRenderTexture(screenTexture);
#else
                        Texture2D screenTexture = ScreenCapture.CaptureScreenshotAsTexture();
#endif

                        // Create a render texture to render into
                        RenderTexture rt = RenderTexture.GetTemporary(targetWidth, targetHeight);

                        if (SystemInfo.graphicsUVStartsAtTop)
                        {
                            Graphics.Blit(screenTexture, rt, new Vector2(1.0f, -1.0f), new Vector2(0.0f, 1.0f));
                        }
                        else
                        {
                            Graphics.Blit(screenTexture, rt);
                        }

                        RenderTexture previousActiveRT = RenderTexture.active;
                        RenderTexture.active = rt;

                        // Create a texture & read data from the active RenderTexture
                        result = new Texture2D(targetWidth, targetHeight, TextureFormat.RGB24, false);
                        result.ReadPixels(new Rect(0, 0, targetWidth, targetHeight), 0, 0);
                        result.Apply();

                        // Reset to initial state
                        RenderTexture.active = previousActiveRT;

                        RenderTexture.ReleaseTemporary(rt);

#if UNITY_2019_1_OR_NEWER
                        RenderTexture.ReleaseTemporary(screenTexture);
#else
                        GameObject.Destroy(screenTexture);
#endif
                    }
                    else
                    {
                        result = ScreenCapture.CaptureScreenshotAsTexture();
                    }

                    File.WriteAllBytes(screenshotPath, result.EncodeToJPG(ScreenshotQuality));
                    GameObject.Destroy(result);

                    _lastScreenTime = BacktraceDatabase.LastFrameTime;
                    _lastScreenPath = screenshotPath;
                }
            }
            return screenshotPath;
        }



        /// <summary>
        /// Get path to Unity player logs.
        /// </summary>
        /// <returns>Path to unity player log</returns>
        private string GetUnityPlayerLogFile(BacktraceData backtraceData, string dataPrefix)
        {
            if (!_settings.AddUnityLogToReport)
            {
                return string.Empty;
            }
            var playerLogPath =
#if UNITY_STANDALONE_LINUX
                    string.Format("~/.config/unity3d/{0}/{1}/Player.log", Application.companyName, Application.productName);
#elif UNITY_STANDALONE_OSX
                    string.Format("~/Library/Logs/{0}/{1}/Player.log", Application.companyName, Application.productName);
#elif UNITY_STANDALONE_WIN
                    Path.Combine(
                        Directory.GetParent(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)).FullName,
                        "LocalLow",
                        Application.companyName,
                        Application.productName,
                        "Player.log");
#else
            string.Empty;
#endif
            if (string.IsNullOrEmpty(playerLogPath) || !File.Exists(playerLogPath))
            {
                return string.Empty;
            }
            var databaseLogPath = Path.Combine(_settings.DatabasePath, string.Format("{0}-lg.log", dataPrefix));
            File.Copy(playerLogPath, databaseLogPath);
            return databaseLogPath;
        }
    }
}
