using Backtrace.Unity.Model;
using System;

namespace Backtrace.Unity.Interfaces
{
    /// <summary>
    /// Backtrace client interface. Use this interface with dependency injection features
    /// </summary>
    public interface IBacktraceClient
    {
        /// <summary>
        /// Send a new report to a Backtrace API
        /// </summary>
        /// <param name="report">New backtrace report</param>
        void Send(BacktraceReport report, Action<BacktraceResult> sendCallback);

        /// <summary>
        /// Set client report limit in Backtrace API
        /// </summary>
        /// <param name="reportPerMin"></param>
        void SetClientReportLimit(uint reportPerMin);

        /// <summary>
        /// Allow Backtrace client to handle all unhandled exception generated by environment
        /// </summary>
        void HandleUnhandledExceptions();
      
        /// <summary>
        /// Refresh client configuration
        /// </summary>
        void Refresh();
    }
}