name: Test package

on:
    push:
        branches: [master]
    pull_request:

jobs:
  test:
    name: Run Tests in ${{ matrix.testMode }} ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
          # - editmode
        projectPath:
          - test-package
        unityVersion:
          # LTS License
          #- 2021.3.48f1
          - 2022.3.56f1
          - 6000.0.38f1
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Environment
        run: |
          mkdir ${{ matrix.projectPath }}
          mv Editor Runtime Tests Android iOS Windows package.json ${{ matrix.projectPath }}/

      - name: Run Tests
        uses: game-ci/unity-test-runner@v4.0.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          packageMode: true
          projectPath: ${{ matrix.projectPath }}/
          testMode: ${{ matrix.testMode }}
          unityVersion: ${{ matrix.unityVersion }}
          coverageOptions: "generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*"